# Generated by Django 3.2 on 2021-12-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpost',
            name='time',
        ),
        migrations.AlterField(
            model_name='quizpost',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry')], max_length=15),
        ),
    ]
