# Generated by Django 3.2 on 2021-12-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211210_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpost',
            name='no_of_question',
        ),
        migrations.AlterField(
            model_name='quizpost',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=15),
        ),
    ]
